# 🔥 Assignment: Exploring PyTorch


## 🎯 Goal
This assignment evaluates your basic skills in using PyTorch, focusing on tensors, autograd, and a small training loop.



### 1️⃣ Setup and Basics
**Task:**

* Install PyTorch and check its version.

* Create a 2D tensor and print it.

In [2]:
import torch

print("PyTorch version:", torch.__version__)
x = torch.tensor([[1., 2.], [3., 4.]])
print("Tensor x:\n", x)


PyTorch version: 2.6.0+cu124
Tensor x:
 tensor([[1., 2.],
        [3., 4.]])


In [3]:
# Your turn:
# Create another tensor y of the same shape with values [[5, 6], [7, 8]].
y = torch.tensor([[5 , 6],[7 , 8]])
print("Tensor y:\n" , y)





Tensor y:
 tensor([[5, 6],
        [7, 8]])


### 2️⃣ Tensor Operations 🧮
**Task:** Perform addition and matrix multiplication.

In [17]:
z = x + y

C = torch.matmul(z, x)#dot

print("Matrix Multiplication:\n", C)


Matrix Multiplication:
 tensor([[30., 44.],
        [46., 68.]])


In [9]:
# Your turn:
# Perform element-wise multiplication (x * y) and print the result.
elementwise_mul = x * y
print("Element-wise Multiplication:\n", elementwise_mul)

#We can write other product , is now:
#>> Object-Oriented product : Chain Operations on both Metrix(ex:result = x.mul(y).add(z).sqrt())
elementwise_mul2 = x.mul(y)
print("Element-wise Multiplication:\n" , elementwise_mul2)
#>> The Function of product : Complex Operations on other Metrix(ex:def scale_tensor(tensor, scale):
    # return torch.mul(tensor, scale))
elementwise_mul3 = torch.mul(x , y)
print("Element-wise Multiplication:\n" , elementwise_mul3)

Element-wise Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Element-wise Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Element-wise Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])


### 3️⃣ Autograd and Gradients ⚙️
**Task:** Enable gradient tracking and compute derivatives.

In [21]:
a = torch.tensor(3.0, requires_grad=True)
b = (a ** 2) + 2 * a + 1
b.backward()
print("Gradient of b wrt a:", a.grad)

Gradient of b wrt a: tensor(8.)
tensor(3., requires_grad=True)
tensor(16., grad_fn=<AddBackward0>)


In [22]:
# Your turn:
# Create a tensor p with value 2.0 (requires_grad=True) and compute the gradient of q = p^3 + 4p.

# Step 1: Create a tensor p with value 2.0 and enable gradient tracking
p = torch.tensor(2.0, requires_grad=True)

# Step 2: Define the function q = p^3 + 4p
# This function will be used for automatic differentiation
q = p ** 3 + 4 * p

# Step 3: Compute the gradient of q with respect to p
# This means we are calculating dq/dp
q.backward()

# Step 4: Print the gradient value
# This should be dq/dp = 3*p^2 + 4 = 3*4 + 4 = 16.0 when p = 2
print("Gradient of q with respect to p:", p.grad)





Gradient of q with respect to p: tensor(16.)


### 4️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (2, 3) and find its max and min.

In [27]:
# Create a random tensor of shape (2, 3) with values in range [0.0, 1.0)
rand_tensor = torch.rand((2, 3))
# Print the generated random tensor
print("Random Tensor:\n", rand_tensor)
# Find and print the maximum value in the tensor
print("Max:", torch.max(rand_tensor))
# Find and print the minimum value in the tensor
print("Min:", torch.min(rand_tensor))

# Advanced Operations:

print("Mean value:", torch.mean(rand_tensor))
print("Std deviation:", torch.std(rand_tensor))
print("Variance:", torch.var(rand_tensor))

#Max and min per row (dim=1)

print("\nMax per row:", torch.max(rand_tensor, dim=1).values)
print("Min per row:", torch.min(rand_tensor, dim=1).values)

#Max and min per column (dim=0)

print("\nMax per column:", torch.max(rand_tensor, dim=0).values)
print("Min per column:", torch.min(rand_tensor, dim=0).values)

#Index of max and min

flat_max_index = torch.argmax(rand_tensor)
flat_min_index = torch.argmin(rand_tensor)

print("\nIndex of max value (flattened):", flat_max_index.item())
print("Index of min value (flattened):", flat_min_index.item())

Random Tensor:
 tensor([[0.0848, 0.7395, 0.4060],
        [0.6347, 0.0163, 0.9611]])
Max: tensor(0.9611)
Min: tensor(0.0163)
Mean value: tensor(0.4737)
Std deviation: tensor(0.3739)
Variance: tensor(0.1398)

Max per row: tensor([0.7395, 0.9611])
Min per row: tensor([0.0848, 0.0163])

Max per column: tensor([0.6347, 0.7395, 0.9611])
Min per column: tensor([0.0848, 0.0163, 0.4060])

Index of max value (flattened): 5
Index of min value (flattened): 4


### 5️⃣ Mini Training Loop 🤖
**Task:** Train a simple linear model y = wx + b using gradient descent.

In [29]:
# Data
x_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0]])

# Model
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Training
learning_rate = 0.01
for epoch in range(100):
    y_pred = w * x_train + b
    loss = torch.mean((y_pred - y_train) ** 2)
    loss.backward()

    # Update
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()

print("Trained weight:", w.item())
print("Trained bias:", b.item())


Trained weight: 1.5541613101959229
Trained bias: 1.013465404510498


### 6️⃣ Bonus ⚡
* Convert a PyTorch tensor to a NumPy array.

* Convert it back to a PyTorch tensor.

In [30]:
# To do
import numpy as np

# Step 1: Create a PyTorch tensor
tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("Original PyTorch Tensor:\n", tensor)

# Step 2: Convert it to a NumPy array
np_array = tensor.numpy()
print("Converted to NumPy Array:\n", np_array)

# Step 3: Convert it back to a PyTorch tensor
converted_back = torch.from_numpy(np_array)
print("Converted back to PyTorch Tensor:\n", converted_back)

Original PyTorch Tensor:
 tensor([[1., 2.],
        [3., 4.]])
Converted to NumPy Array:
 [[1. 2.]
 [3. 4.]]
Converted back to PyTorch Tensor:
 tensor([[1., 2.],
        [3., 4.]])
